scan_filter_chain:
  ros__parameters:
    filter1:
      name: self_box_filter
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: chassis
        min_x: -0.02
        max_x: 1.10
        min_y: -0.33
        max_y: 0.33
        min_z: -0.08
        max_z: 0.20
        invert: false