twist_mux:
  ros__parameters:
    topics:
      safety:
        topic: /cmd_vel_safety
        timeout: 0.15
        priority: 255
      joystick:
        topic: /cmd_vel_joy_safe
        timeout: 0.20
        priority: 100
      navigation:
        topic: /cmd_vel_nav_safe
        timeout: 0.20
        priority: 10
